### ISSUE TITLE
Google assistant wont play a specific song when asked to use spotify dogfood

### ISSUE THREAD

**Issue by AuraTheBatPone** [sergiocastell/spotify-dogfood#23]
Replys with
"Choosing songs is only available to spotify subscribers"

**Comment by sergiocastell** [comment]
From what I know, Spotify app doesn't handle that, but Google Assistant connects (through the oAUTH dialog you allow on the first app connect) to the Spotify API, checks your account status (whether you're free or paid up user), and acts as so.  

Given that, I'm afraid I can't help since the user account status in Spotify remains as Free even though you use a Dogfood-ed version or not.  

Sorry.

**Comment by happenis** [comment]
Darn. I just created an account here so I could ask the same thing. I use Google Assistant all the time and I was really hoping I could request songs while driving.

Nice job though. Although I prefer the))l

**Comment by happenis** [comment]
Oh my. 4:20 am and I literally fell asleep while withing this.
I meant to say that I prefer the green logo. Just used to it I guess

**Comment by the4anoni** [comment]
@sergiocastell  Close issue
